services:
  db:
    image: mysql:5.7
    volumes:
      - "C:/tfmdb:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mabills
      MYSQL_USER: dev
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: dev
