services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    volumes:
      - "/Users/bate.ye/Desktop/iwmaster/TFM/db:/var/lib/mysql"
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: mabills
      MYSQL_USER: dev
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: dev
    user: 502:12
networks:
  default:
    external:
      name: mabills
